apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpc-client-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: grpc-client
            image: movie-client:local
            imagePullPolicy: Always
          restartPolicy: OnFailure
