apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpc-client-job
  namespace: movie-app
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: grpc-client
            image: movie-client:local
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
