# movie-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-controller
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-controller
  template:
    metadata:
      labels:
        app: movie-controller
    spec:
      containers:
        - name: movie-controller
          image: movie-controller:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "movie-controller"
          ports:
            - name: grpc
              containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: movie-controller
  namespace: movie-app
spec:
  selector:
    app: movie-controller
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
