# movie-recommender.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-recommender
  template:
    metadata:
      labels:
        app: movie-recommender
    spec:
      containers:
        - name: movie-recommender
          image: movie-recommender:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "movie-recommender"
          ports:
            - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: movie-recommender
  namespace: movie-app
spec:
  selector:
    app: movie-recommender
  ports:
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: 50054
