apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: movie-app
data:
  tempo.yaml: |
    server:
      log_level: info
      http_listen_address: 0.0.0.0
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317

    ingester: {}

    compactor: {}

    metrics_generator: {}

    querier: {}

    query_frontend: {}

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
