# movie-store.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-store
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-store
  template:
    metadata:
      labels:
        app: movie-store
    spec:
      containers:
        - name: movie-store
          image: movie-store:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "movie-store"
          ports:
            - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: movie-store
  namespace: movie-app
spec:
  selector:
    app: movie-store
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
