# user-preferences.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-preferences
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-preferences
  template:
    metadata:
      labels:
        app: user-preferences
    spec:
      containers:
        - name: user-preferences
          image: user-preferences:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "user-preferences"
          ports:
            - containerPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: user-preferences
  namespace: movie-app
spec:
  selector:
    app: user-preferences
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50053
